### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Armature Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#10]
UPBGE Manual » Logic Bricks » Actuators » Armature Actuator
https://upbge.org/manual/manual/logic/actuators/types/armature.html

"Used to change the Influence of a constraint by selecting a new weight with the Influence field"
should be:
"Used to change the influence of a constraint by selecting a new influence with the Influence field"

**Comment by ShaunKulesa** [comment]
will do

**Comment by lordloki** [comment]
In this case i'm not sure if it is wrong because with the influence you modify the "weight" of the constraint over the object/vertex to be constrained
