### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Action Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#11]
UPBGE Manual » Logic Bricks » Actuators » Action Actuator
https://upbge.org/manual/manual/logic/actuators/types/action.html

"It is only visible when an armature is selected, because the actions are stored in the armature."
is wrong, as the Action Actuator is visible when the default cube is selected, for example.

**Comment by lordloki** [comment]
Fixed. Thanks for pointing out.
