### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Action Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#12]
UPBGE Manual » Logic Bricks » Actuators » Action Actuator
https://upbge.org/manual/manual/logic/actuators/types/action.html

"Loop End
    Play F-Curve continuously from end to start when a TRUE pulse is received."
should be:
"Loop End
    Play F-Curve continuously from start to end when a TRUE pulse is received."

***

"Loop Start
    Play F-Curve continuously from start to end when a TRUE pulse is received."
should be:
"Loop Stop
    Play F-Curve continuously from start to end when a TRUE pulse is received. Stop when a FALSE pulse is received."

**Comment by lordloki** [comment]
Thanks for the fix. Committed.
