### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Constraints Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#13]
UPBGE Manual » Logic Bricks » Actuators » Constraints Actuator
https://upbge.org/manual/manual/logic/actuators/types/constraint.html

In section "Distance Constraint":
"Property/Material that triggers the Force Field constraint (blank for all Properties/Materials)."
should be:
"Property/Material that triggers the Distance Constraint (blank for all Properties/Materials)."

**Comment by ShaunKulesa** [comment]
I'll take this one @lordloki :)

**Comment by ShaunKulesa** [comment]
done

**Comment by lordloki** [comment]
Thanks!! closing.
