### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Constraints Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#14]
UPBGE Manual » Logic Bricks » Actuators » Constraints Actuator
https://upbge.org/manual/manual/logic/actuators/types/constraint.html

In section "Distance Constraint":
"Persistence button: When on, force field constraint always looks at Property/Material; when off, turns itself off if it cannot find the Property/Material."
should be:
"Persistence button: when on, Distance Constraint always looks for Property/Material; when off, turns itself off if it cannot find the Property/Material."

**Comment by lordloki** [comment]
Committed. Thanks for the fix
