### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator: corrections

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#15]
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator
https://upbge.org/manual/manual/logic/actuators/types/edit_object.html

In section "Dynamics":

"Disable Rigid Body
    Disables the Rigid Body state of the object – disables collision."
should be something like:
"Disable Rigid Body
    Disables the Rigid Body state of the object, it then behaves like a Dynamic object (no rotation)."

***

"Enable Rigid Body
    Disables the Rigid Body state of the object – enables collision."
should be something like:
"Enable Rigid Body
    Enables the Rigid Body state of the object – enables rotation."

**Comment by lordloki** [comment]
Fixed in master. Thanks for the fix. Closing
