### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator: undocumented feature

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#16]
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator
https://upbge.org/manual/manual/logic/actuators/types/edit_object.html

In section "Dynamics", "Suspend Physics" and "Restore Physics" are undocumented...

Documentation could be something like:
"
Suspend Physics
    Suspends the object physics (disables object velocity and collision).

Restore Physics
    Resumes the object physics (enables object velocity and collision).
"

**Comment by lordloki** [comment]
Committed in master. Thanks for the proposal. Closing
