### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator: undocumented feature

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#17]
UPBGE Manual » Logic Bricks » Actuators » Edit Object Actuator
https://upbge.org/manual/manual/logic/actuators/types/edit_object.html

In section "Track To", "Up Axis" and "Track Axis" are undocumented...

The sentence "The Y axis is considered the front of the object." should be removed.
Documentation could be something like:
"
Up Axis
    Selects the axis that should point up.
    
Track Axis
    Selects the axis that should point to the target object.
"

**Comment by lordloki** [comment]
Change committed. Thanks for the proposal. Closing
