### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Filter 2D Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#18]
UPBGE Manual » Logic Bricks » Actuators » Filter 2D Actuator
https://upbge.org/manual/manual/logic/actuators/types/filter_2d.html

Caption of first screenshot:
"Edit Object actuator."
should be:
"Filter 2D actuator."

**Comment by lordloki** [comment]
Thanks for the fix. Committed.
