### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Game Actuator: undocumented feature

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#19]
UPBGE Manual » Logic Bricks » Actuators » Game Actuator
https://upbge.org/manual/manual/logic/actuators/types/game.html

"Screenshot" is undocumented.
Documentation could be something like:
'
Screenshot
    Save a screenshot to the specified file.
    File
        Path to the screenshot to save (".png" is appended to the filename).
'

**Comment by lordloki** [comment]
Thanks for the patch. Committed
