### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Mouse Actuator: many corrections

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#21]
UPBGE Manual » Logic Bricks » Actuators » Mouse Actuator
https://upbge.org/manual/manual/logic/actuators/types/mouse.html

The following sentence belongs to "Motion Actuator":
"Servo control is a powerful way to achieve motion in way which mimics the movement of objects in the physical world. It consists in a servo controller that adjusts the force on the object in order to achieve a given speed."

In the rest of the document, each parameter description, from "Use X axis, Y axis" to "Object axis X, Y, Z", actually belongs to "Motion Actuator". For example, the description of "Use X axis, Y axis" is actually the description of "Reference Object" in section "Servo Control" of "Motion Actuator"...

**Comment by lordloki** [comment]
Fixed. Thanks for reporting
