### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Motion Actuator: update

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#22]
UPBGE Manual » Logic Bricks » Actuators » Motion Actuator
https://upbge.org/manual/manual/logic/actuators/types/motion.html

In section "Servo Control", since "Servo Type" has been added (with 2 choices, "Linear" and "Angular"), this sentence is no longer correct:
"Only the positional velocity is influenced by this actuator; it does not control rotation at all, and it controls position only indirectly."
It should be replaced with something like:
"This actuator controls position or rotation only indirectly."

**Comment by lordloki** [comment]
Fixed in current master. That chapter is not totally reworked. I'm doing several changes there yet.

Thanks for the fix.
