### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Motion Actuator: corrections

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#23]
UPBGE Manual » Logic Bricks » Actuators » Motion Actuator
https://upbge.org/manual/manual/logic/actuators/types/motion.html

The sentence:
"There are two modes of operation, Simple or Servo,"
should be:
"There are three modes of operation, Simple, Servo and Character,"

***

For "Angular Velocity", the sentence:
"The target linear velocity for the object."
should be:
"The target angular velocity for the object."

***

In section "Character Motion", for "Jump", the sentence:
"The character performs the jump previously configured."
could be:
"Make the character jump using the settings in the physics properties (Jump Force and Max Jumps)."

**Comment by lordloki** [comment]
Committed. thanks
