### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Sound Actuator: correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#24]
UPBGE Manual » Logic Bricks » Actuators » Sound Actuator
https://upbge.org/manual/manual/logic/actuators/types/sound.html

For "Play End", the sentence:
"The sound is not replayed if activated while still playing."
should be:
"The sound is replayed if activated while still playing."

**Comment by lordloki** [comment]
Included in master. Thanks
