### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Steering Actuator: corrections

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#25]
UPBGE Manual » Logic Bricks » Actuators » Steering Actuator
https://upbge.org/manual/manual/logic/actuators/types/steering.html

- "Lock Z velocity" is undocumented (tooltip says "Disable simulation of linear motion along Z axis.").
- "Visualize": maybe it should be specified that it's only for "Path following" behavior.
- "Visualize": the sentence "It is also necessary to enable Debug Properties in the Display menu of the Render tab." should be removed.

**Comment by lordloki** [comment]
Included in master. Thanks
