### ISSUE TITLE
UPBGE Manual » Logic Bricks » Properties: update

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#26]
UPBGE Manual » Logic Bricks » Properties
https://upbge.org/manual/manual/logic/properties.html

The sentence:
"To turn debugging on, tick the Show Debug Properties checkbox in the Game menu."
should be something like:
"To turn debugging on, tick the Debug Properties checkbox in the Game Debug panel of the Render Properties."

**Comment by lordloki** [comment]
Included in master. Thanks
