### ISSUE TITLE
UPBGE Manual » Python Scripting » Introduction to Scripting: corrections

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#27]
UPBGE Manual » Python Scripting » Introduction to Scripting
https://upbge.org/manual/manual/python/introduction.html

Code snippet:
`for i in range(10): exec("var\_%d = %d" % (i,i))`
- should be indented.
- '_' shouldn't be escaped ("SyntaxError: invalid escape sequence").

Corrected snippet:
```
for i in range(10):
    exec("var_%d = %d" % (i,i))
```

***

Right after that:
"
This snip of code is the equivalent to the following:

```
var_1 = 1

var_2 = 3

var_3 = 3

(...)
```
"
should be:
"
This snip of code is the equivalent to the following:

```
var_0 = 0

var_1 = 1

var_2 = 2

(...)
```
"

**Comment by lordloki** [comment]
Commited. Thanks for the fix.
