### ISSUE TITLE
I don't want anything to do with UPBGE or contributions to it, you can keep my words and photos but I just don't want my name on the front.

### ISSUE THREAD

**Issue by ShaunKulesa** [UPBGE/UPBGE-Docs#32]

**Comment by lordloki** [comment]
Agreed. Anyway, thanks for your contributions.

**Comment by ShaunKulesa** [comment]
Last thing, I'm only doing this because I got banned without warning and for something I don't recall doing. I may still contribute 2d filters once I learn how to do them.
