### ISSUE TITLE
UPBGE Manual - Logic Bricks - Sensors - Movement Sensor not included

### ISSUE THREAD

**Issue by arch-sketch** [UPBGE/UPBGE-Docs#35]
https://upbge.org/manual/manual/logic/sensors/index.html

The Movement Sensor is not included in the manual.  

There is a page describing it in the upbge API: https://upbge.org/api/bpy.types.MovementSensor.html?highlight=movement%20sensor

**Comment by lordloki** [comment]
Fixed in master. Thanks for reporting.

**Comment by youle31** [comment]
Thanks!
