### ISSUE TITLE
The page "https://upbge.org/manual/manual/" don't exists

### ISSUE THREAD

**Issue by uayten** [UPBGE/UPBGE-Docs#36]
The first page of UPBGE Manual is: https://upbge.org/manual/
And any other page is: https://upbge.org/manual/manual/introduction/index.html
And this page in betwen don't exists: https://upbge.org/manual/manual/

I am currently developing the Logic Nodes documentation and placing the links, but I found this "syntax" error in the links.
I would like to know if there is a possibility to remove "...manual/" from the link, because in the future it would be a hard job to change the links all back to the correct ones

**Comment by lordloki** [comment]
basically, that structure comes from here:
public_html directory
|----- manual directory -> https://upbge.org/manual/index.html
|----- manual 0.2.5 -> https://upbge.org/manual_api_0.2.5/index.html

The structure of these manual is created automatically, then when we click in introduction or in logic nodes chapter we get -> https://upbge.org/manual/manual/logic_nodes/index.html

For the 0.2.5 we would get -> https://upbge.org/manual_api_0.2.5/manual/introduction/index.html

Summarizing, the double manual/manual won't be remove in the future. Anyway, you can use relative links.

BTW, do you need write access to this repository? Perhaps, it would help you developing the documentation.

**Comment by uayten** [comment]
Yes, I am currently doing the documentation in .md files on the recommendation of Iza Zed (Discord Nickname)
It would be a good help to be able to edit on the site.

**Comment by lordloki** [comment]
I just sent you a write access invitation

**Comment by uayten** [comment]
I accepted the invitation, but how do I edit logic nodes now?

**Comment by uayten** [comment]
i figure out, thank you
