### ISSUE TITLE
Attributes no longer read-only? 

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/UPBGE-Docs#4]
It says here that the attributes are read-only only: 
https://github.com/UPBGE/UPBGE-Docs/blob/master/source/api/bge.types.KX_Scene.rst

That is not true anymore? At least not for UPGE 0.3 Alpha, build for Windows x64 2020-09-29. 

I could do this in a script for instance : 

`objects = (bge.logic.getCurrentScene()).objects`
`objects["mycube"].applyRotation( [0,0.1,0],True )`

The controller had a different owner than `mycube` , but cube was sure rotating. 

Could be nice to clarify that the attributes are not read-only anymore (or?). 

UPGE 0.3 is awesome btw.

**Comment by BluePrintRandom** [comment]
they never were !

if you have a ref to a gameOb you can act on it directly in py - however you can't trigger an actuator from the outside*
cont = own.scene.objects['Bob'].controllers['Python']
cont.activate(cont.actuators['Motion']) #does not work
