### ISSUE TITLE
Scenes aren't used anymore

### ISSUE THREAD

**Issue by MechatronixX** [UPBGE/UPBGE-Docs#5]
Trying to create my first HUD in UPBGE 0.3 alpha, a bit confused. Most people seemed to use addScene() previously. Now I finally found why that doesn't work: 

https://github.com/UPBGE/upbge/issues/1167

So for instance this should probably be updated: 
https://upbge-docs.readthedocs.io/en/latest/api/bge.logic.html?highlight=addscene#bge.logic.addScene

**Comment by lordloki** [comment]
Yes, we need to replace that scene part with collection actuator one

**Comment by ShaunKulesa** [comment]
I will fix that either tommorow or the weekend. You have my word!
