### ISSUE TITLE
UPBGE Manual » Logic Bricks » Controllers » Controller Editing: tiny correction

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#6]
Not sure this is the right way to go about such a tiny correction... Please let me know.
Here it is:
UPBGE Manual » Logic Bricks » Controllers » Controller Editing
https://upbge.org/manual/manual/logic/controllers/editing.html
"X Button
Deletes the sensor."
should be:
"X Button
Deletes the controller."

**Comment by lordloki** [comment]
Thanks for the fix. Commited
