### ISSUE TITLE
UPBGE Manual » Logic Bricks » Controllers » XOR Controller: tiny correction (grammar)

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#7]
UPBGE Manual » Logic Bricks » Controllers » XOR Controller
https://upbge.org/manual/manual/logic/controllers/types/xor.html

"when One (and only one) of its inputs are TRUE"
should be:
"when One (and only one) of its inputs is TRUE"

**Comment by ShaunKulesa** [comment]
Fixed!
