### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Actuator Editing: missing words

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#8]
UPBGE Manual » Logic Bricks » Actuators » Actuator Editing
https://upbge.org/manual/manual/logic/actuators/editing.html

"The column headings contain controls to set which actuators, and the level of detail given, in the actuator column."
should be (something like):
"The column headings contain controls to set which actuators are displayed, and the level of detail given, in the actuator column."

**Comment by lordloki** [comment]
Thanks. Fixed
