### ISSUE TITLE
UPBGE Manual » Logic Bricks » Actuators » Armature Actuator: swapped words

### ISSUE THREAD

**Issue by denicolas** [UPBGE/UPBGE-Docs#9]
UPBGE Manual » Logic Bricks » Actuators » Armature Actuator
https://upbge.org/manual/manual/logic/actuators/types/armature.html

"The Armature Actuator only is available for armature objects."
should be:
"The Armature Actuator is only available for armature objects."

**Comment by lordloki** [comment]
Fixed. Thanks
